version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

